spring.application.name=backend
server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/zzan?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234


mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml
jwt.secret=your-256-bit-long-secret-key-here

jwt.expiration=3600000


toss.secret.key=test_sk_6BYq7GWPVvPY2DOJGEEL8NE5vbo1


logging.level.org.springframework=DEBUG
